# Generated by Django 5.2.13 on 2026-05-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_plain_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plain_password',
        ),
    ]
