import { useEffect, useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { adminListUsers, adminToggleUserActive } from "../api/authApi";
import { useAuth } from "../context/AuthContext";

export default function AdminUsersPage() {
  const { handleLogout } = useAuth();
  const location = useLocation();
  const [users, setUsers] = useState([]);
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const loadUsers = async () => {
    setLoading(true);
    try {
      const { data } = await adminListUsers(search);
      setUsers(data);
    } catch {
      setError("Unable to fetch users.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadUsers();
  }, []);

  useEffect(() => {
    if (location.state?.wasAutogenerated) {
      alert(
        `Security Warning:\nYour password "${location.state.tempPass}" is autogenerated and simple, therefore less secure. Please go to Edit Profile and set a custom password.`
      );
      window.history.replaceState({}, document.title);
    }
  }, [location.state]);

  const toggleStatus = async (id) => {
    await adminToggleUserActive(id);
    loadUsers();
  };

  return (
    <main className="page">
      <header className="topbar">
        <h1>Admin - Users</h1>
        <button className="btn" onClick={handleLogout}>
          Logout
        </button>
      </header>
      <section className="card">
        <div className="controls">
          <input
            placeholder="Search users"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && loadUsers()}
          />
          <button className="btn" onClick={loadUsers}>
            Search
          </button>
        </div>
        {loading ? (
          <p>Loading...</p>
        ) : (
          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Full Name</th>
                  <th>Email</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {users.map((user) => (
                  <tr key={user.id}>
                    <td>{user.full_name}</td>
                    <td>{user.email}</td>
                    <td className="action-row">
                      <Link className="btn light-blue" to={`/admin/users/${user.id}`}>
                        Edit
                      </Link>
                      <button
                        className={`btn ${user.is_active ? "light-red" : "light-green"}`}
                        onClick={() => toggleStatus(user.id)}
                        disabled={user.role === "admin"}
                        title={user.role === "admin" ? "Admins cannot be inactivated" : ""}
                      >
                        {user.is_active ? "Inactivate" : "Activate"}
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
        {error && <p className="error">{error}</p>}
      </section>
    </main>
  );
}
