import { useEffect, useMemo, useState } from "react";
import { FiPlus } from "react-icons/fi";
import { Link, useNavigate, useLocation } from "react-router-dom";
import { deleteNote, fetchMonthNotes, fetchNoteByDate, saveNote, updateNote } from "../api/noteApi";
import CalendarGrid from "../components/CalendarGrid";
import NoteModal from "../components/NoteModal";
import { useAuth } from "../context/AuthContext";

function currentDateString() {
  const d = new Date();
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

function currentMonthString() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
}

export default function DashboardPage() {
  const { user, handleLogout } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const [selectedDate, setSelectedDate] = useState(currentDateString());
  const [currentMonth, setCurrentMonth] = useState(currentMonthString());
  const [notesByDate, setNotesByDate] = useState({});
  const [showModal, setShowModal] = useState(false);
  const [existingNote, setExistingNote] = useState(null);
  const [formContent, setFormContent] = useState("");
  const [jumpDate, setJumpDate] = useState(currentDateString());
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const title = useMemo(() => `${user?.first_name || user?.username}'s Calendar`, [user]);

  const handleJump = () => {
    if (!jumpDate) return;
    setSelectedDate(jumpDate);
    const [y, m] = jumpDate.split("-");
    setCurrentMonth(`${y}-${m}`);
  };

  const loadMonth = async () => {
    const [year, month] = currentMonth.split("-");
    const { data } = await fetchMonthNotes(year, month);
    const map = {};
    data.forEach((note) => {
      map[note.date] = note;
    });
    setNotesByDate(map);
  };

  useEffect(() => {
    loadMonth();
  }, [currentMonth]);

  useEffect(() => {
    if (location.state?.wasAutogenerated) {
      alert(
        `Security Warning:\nYour password "${location.state.tempPass}" is autogenerated and simple, therefore less secure. Please go to Edit Profile and set a custom password.`
      );
      // Clear the state so the alert doesn't keep popping up
      window.history.replaceState({}, document.title);
    }
  }, [location.state]);

  const openModal = async () => {
    setError("");
    setLoading(true);
    setShowModal(true);
    try {
      const { data } = await fetchNoteByDate(selectedDate);
      setExistingNote(data.note);
      setFormContent(data.note?.content || "");
    } catch {
      setError("Unable to fetch note.");
    } finally {
      setLoading(false);
    }
  };

  const onSave = async () => {
    if (!formContent.trim()) return;
    setLoading(true);
    try {
      if (existingNote) {
        await updateNote(existingNote.id, { date: selectedDate, content: formContent });
      } else {
        await saveNote({ date: selectedDate, content: formContent });
      }
      await loadMonth();
      const refreshed = await fetchNoteByDate(selectedDate);
      setExistingNote(refreshed.data.note);
      setFormContent(refreshed.data.note?.content || "");
    } catch {
      setError("Unable to save note.");
    } finally {
      setLoading(false);
    }
  };

  const onDelete = async () => {
    if (!existingNote) return;
    setLoading(true);
    try {
      await deleteNote(existingNote.id);
      await loadMonth();
      setExistingNote(null);
      setFormContent("");
      setShowModal(false);
    } catch {
      setError("Unable to delete note.");
    } finally {
      setLoading(false);
    }
  };

  const onMonthChange = (delta) => {
    const [y, m] = currentMonth.split("-").map(Number);
    const d = new Date(y, m - 1 + delta, 1);
    setCurrentMonth(`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`);
  };

  const handleSelectDate = (date) => {
    if (date === selectedDate) {
      openModal();
    } else {
      setSelectedDate(date);
    }
  };

  return (
    <main className="dashboard-page">
      <header className="topbar">
        <button className="link-button" onClick={() => navigate(user.role === "admin" ? "/admin/users" : "/dashboard")}>
          Dashboard
        </button>
        <Link className="calendar-title" to="/profile">
          {title}
        </Link>
        <button className="btn" onClick={handleLogout}>
          Logout
        </button>
      </header>

      <section className="controls">
        <p>Selected date: {selectedDate}</p>
        <div className="jump-to">
          <input type="date" value={jumpDate} onChange={(e) => setJumpDate(e.target.value)} />
          <button className="btn" onClick={handleJump}>
            Go to Date
          </button>
        </div>
        <button className="btn primary" onClick={openModal}>
          <FiPlus /> Add Note
        </button>
      </section>

      <CalendarGrid
        selectedDate={selectedDate}
        onSelectDate={handleSelectDate}
        notesByDate={notesByDate}
        currentMonth={currentMonth}
        onMonthChange={onMonthChange}
      />

      {error && <p className="error">{error}</p>}
      {showModal && (
        <NoteModal
          selectedDate={selectedDate}
          formContent={formContent}
          setFormContent={setFormContent}
          existingNote={existingNote}
          onSave={onSave}
          onDelete={onDelete}
          onClose={() => setShowModal(false)}
          loading={loading}
        />
      )}
    </main>
  );
}
