import { useEffect, useState } from "react";
import { Link, useNavigate, useLocation } from "react-router-dom";
import PasswordField from "../components/PasswordField";
import { useAuth } from "../context/AuthContext";
import { parseError } from "../utils/errorParser";

export default function LoginPage() {
  const navigate = useNavigate();
  const { search } = useLocation();
  const { handleLogin } = useAuth();
  const [form, setForm] = useState({ username: "", password: "", remember_me: false });
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const params = new URLSearchParams(search);
    const username = params.get("username");
    const password = params.get("password");
    if (username && password) {
      setForm((prev) => ({ ...prev, username, password }));
    }
  }, [search]);

  const onChange = (event) => {
    const { name, type, checked, value } = event.target;
    setForm((prev) => ({ ...prev, [name]: type === "checkbox" ? checked : value }));
  };

  const onSubmit = async (event) => {
    event.preventDefault();
    setLoading(true);
    setError("");
    try {
      const isAutogenerated = form.password === `${form.username}@123456789`;
      const data = await handleLogin(form);
      navigate(data.user.role === "admin" ? "/admin/users" : "/dashboard", {
        state: { wasAutogenerated: isAutogenerated, tempPass: form.password },
      });
    } catch (err) {
      setError(parseError(err?.response?.data) || "Unable to login.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <main className="auth-page">
      <form className="card form-card" onSubmit={onSubmit}>
        <h1>Login</h1>
        <label className="field">
          <span>Username or Email</span>
          <input name="username" value={form.username} onChange={onChange} required />
        </label>
        <PasswordField label="Password" name="password" value={form.password} onChange={onChange} required />
        <label className="checkbox">
          <input type="checkbox" name="remember_me" checked={form.remember_me} onChange={onChange} />
          <span>Remember me (up to 1 year)</span>
        </label>
        {error && <p className="error">{error}</p>}
        <button className="btn primary" disabled={loading} type="submit">
          {loading ? "Logging in..." : "Login"}
        </button>
        <div className="auth-links">
          <Link to="/register">Create account</Link>
          <Link to="/forgot-password">Forgot password?</Link>
        </div>
      </form>
    </main>
  );
}
